### ISSUE TITLE
It’d be great to pipe stuff in

### ISSUE THREAD

**Issue by tomekwi** [maxogden/electron-spawn#10]
```sh
$ browserify test.js > electron-spawn
```

If that worked, I’d jump all over the place shouting out with joy!

Perhaps I’ll find the time to help you guys implement it :)

**Comment by shama** [comment]
That is currently possible with [testron](https://github.com/shama/testron#writing-tests) which uses `electron-spawn` under the hood.

It only supports TAP atm though: `browserify test.js | testron`

**Comment by maxogden** [comment]
@dominictarr also implemented this in https://github.com/dominictarr/electro (he didn't know about this module before). but it does STDIN and this one doesn't

**Comment by tomekwi** [comment]
:+1: thanks for the links!
