### ISSUE TITLE
Best way to load and render html

### ISSUE THREAD

**Issue by lastmjs** [maxogden/electron-spawn#19]
What is the best way to load an HTML file and have it render fully, but still headless of course. Is the best way to use BrowserWindow and load the HTML file normally?

**Comment by lastmjs** [comment]
I'm having struggles loading any kind of html file of my own actually. Not sure how to go about it.

**Comment by shama** [comment]
I don't think this library intends to run a custom html file. I think using electron directly would be better suited for this:

`npm install electron-prebuilt -g`

```js
// main.js
var app = require('app')
var BrowserWindow = require('browser-window')
app.on('ready', function () {
  win = new BrowserWindow({show: true})
  win.loadURL('file://' + path.join(__dirname, 'yourfile.html'))
})
```

Then run `electron main.js`

**Comment by lastmjs** [comment]
Maybe I don't understand the purpose of this library then. Isn't running headless electron useful because you can interact with Chromium Dom APIs along with the node APIs? What is the advantage of this library over just node, or PhantomJS? I'm very interested in this library because I want to headlessly run exactly what would have run in an electron app.

**Comment by shama** [comment]
The purpose of this library is to "run code easily inside of headless electron (chromium) windows from the command line" The only difference between this library and running electron directly is this library conveniently sets up a browser window to run code inside of.

So if you are supplying your own electron browser window, you'll be using very little of this library. In which case, why not just use electron directly?

**Comment by lastmjs** [comment]
My use case is headless html rendering with browser code and node code, which is just what Electron offers, but I need to run it in a server environment, with no graphical capabilities. So I want Electron, but completely headless. I made a pull request, and I've got it working on my local machine. I think my pull request is a little hackish though.

**Comment by shama** [comment]
Closing via https://github.com/maxogden/electron-spawn/pull/20#issuecomment-216473257
