### ISSUE TITLE
Suggestion : change dependency to electron-prebuilt into electron

### ISSUE THREAD

**Issue by jpbourgeon** [maxogden/electron-spawn#25]
From electron-prebuilt's readme : 

> Note As of version 1.3.1, this package is published to npm under two names: electron and electron-prebuilt. You can currently use either name, but electron is recommended, as the electron-prebuilt name is deprecated, and will only be published until the end of 2016.

You shoud consider updating your dependency before it is deprecated

**Comment by mafintosh** [comment]
Sounds good. Do you want to send a PR that changes that?

**Comment by jpbourgeon** [comment]
See Pull Request #26
