### ISSUE TITLE
Use scripts.pop()

### ISSUE THREAD

**Issue by TuckerWhitehouse** [maxogden/electron-spawn#5]
Why do two slices when these lines could be replaced with ```opts = scripts.pop()```?
https://github.com/maxogden/electron-spawn/blob/master/index.js#L8-L9

**Comment by shama** [comment]
Because...
![dog](https://cloud.githubusercontent.com/assets/99604/9041830/39158f88-39bf-11e5-9896-577843c628a3.jpg)

Mind sending a PR? :)
