### ISSUE TITLE
Question: Why isn’t electron-prebuilt a dependency?

### ISSUE THREAD

**Issue by tomekwi** [maxogden/electron-spawn#9]
There’s probably a good reason for it – I’m just asking out of curiosity.

I stumbled over it a couple of times – I’m used to all-inclusive npm packages :)

**Comment by shama** [comment]
I believe it is so the user can choose which version or at which install level it exists.

The implementation here is not super tied to a particular version of `electron-prebuilt` but a user of this library will likely write code that will be tied to a particular version of electron.

Also a user can choose to install `electron-prebuilt` once globally if they have limited space (although recommended to install locally whenever possible).

**Comment by maxogden** [comment]
agree with all @shama said, biggest one being that electron is a relatively heavy dependency

**Comment by tomekwi** [comment]
:+1: thanks for the explanation! Makes sense to me.
